apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-2
  namespace: default
  annotations:
    version: "{{ env['VERSION'] }}"
  labels:
    razee/watch-resource: "lite"
data:
  key1: "1"
  key2: "2"
